version: 1.0.{build}
os: Visual Studio 2015
environment:
  MSBUILD_VERBOSITY: normal
build_script:
- ps: .\build.ps1
test_script:
- ps: .\test.ps1
artifacts:
- path: artifacts/Gauge.VisualStudio.vsix
  name: Gauge.VisualStudio
on_finish:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\artifacts\gauge.visualstudio.xml))